version: '3.9'

services:
  flask-backend:
    build:
      context: ./Flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env  # Point to your root .env file

  react-frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  main-controller:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
